### ISSUE TITLE
VSCode changed requires to imports, now all builds are failing

### ISSUE THREAD

**Issue by ScolderCreations** [scratchbackup/scratchbackup.github.io#26]
If someone could revert the commit that caused this, i would be very grateful.

**Comment by hello-smile6** [comment]
I'll try.

**Comment by hello-smile6** [comment]
@ScolderCreations Just undo https://github.com/scratchbackup/scratchbackup.github.io/commit/7b066a4291cdcabd4a9d885ebaaea056052d07b6, I'll open a pull request.

**Comment by hello-smile6** [comment]
Done! Just merge my pull request.

**Comment by ScolderCreations** [comment]
thanks! there was one file that was still broken, but i fixed it manually.
