### ISSUE TITLE
Search Functionality not working for now as intented

### ISSUE THREAD

**Issue by Barthdry** [scratchbackup/scratchbackup.github.io#5]
Need to fix the incomplete search function and make a better user interface for it. Rather than using window.alert();

**Comment by Amritanshu02** [comment]
Hello,I would like to work upon this , could you assign it to me

**Comment by ScolderCreations** [comment]
> Hello,I would like to work upon this , could you assign it to me

You don't need to be assigned to contribute. Just fork the repository, make the changes needed, and make a pull request.
