### ISSUE TITLE
Can't access website!

### ISSUE THREAD

**Issue by RunTheCoins** [scratchbackup/scratchbackup.github.io#80]
Whenever I open this link in chrome or chroniem, it just gives me a blank HTML page...
I have decent internet, idk what the problem is.

**Comment by hello-smile6** [comment]
> Whenever I open this link in chrome or chroniem, it just gives me a blank HTML page... I have decent internet, idk what the problem is.

Screenshot?

**Comment by RunTheCoins** [comment]
> > Whenever I open this link in chrome or chroniem, it just gives me a blank HTML page... I have decent internet, idk what the problem is.
> 
> Screenshot?
![Screen Shot 2022-01-30 at 10 14 33 PM](https://user-images.githubusercontent.com/81893577/151734157-2737a2c6-5ecf-4a17-88ec-d062eb82363b.png)

**Comment by hello-smile6** [comment]
> > > Whenever I open this link in chrome or chroniem, it just gives me a blank HTML page... I have decent internet, idk what the problem is.
> > 
> > 
> > Screenshot?
> > ![Screen Shot 2022-01-30 at 10 14 33 PM](https://user-images.githubusercontent.com/81893577/151734157-2737a2c6-5ecf-4a17-88ec-d062eb82363b.png)

@ScolderCreations `raw.githubusercontent.com` uses `text/plain` for everything! It won't work with that!!!
