### ISSUE TITLE
Page doesnt load

### ISSUE THREAD

**Issue by Quantum-Codes** [scratchbackup/scratchbackup.github.io#94]
Just simply gives a blank black page. Like #80 but black (maybe cuz dark mode)
It shows the website for less than a second and then it's gone. It goes black

**Comment by ScolderCreations** [comment]
Note about the page color when crashes occur:
If it’s white, an error occurred before the page could finish rendering (for example, the HTML in the script is broken)
If it’s black, that means an error occurred during execution of JS code (usually sorting related)

**Comment by hello-smile6** [comment]
Got an idea

**Comment by ScolderCreations** [comment]
> Got an idea

Care to elaborate?

**Comment by ScolderCreations** [comment]
Resolved in the latest build.

**Comment by Quantum-Codes** [comment]
Cam confirm. Works!
